name: development-branch

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.2.0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: ls -R
      - name: yarn install
        run: yarn install
      - run: ls -R
      - name: yarn build
        run: yarn build
      - run: ls -R
