name: master-branch

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.2.0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: yarn install
        run: yarn install
      - name: yarn build
        run: yarn build
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.2.0
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting -P dispersed-lists
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
